apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deploy
spec:
  replicas: 3 # Usamos 3 para probar el balanceo
  selector:
    matchLabels:
      app: ws-app
  template:
    metadata:
      labels:
        app: ws-app
    spec:
      containers:
      - name: ws
        image: tu-usuario-docker/sockets:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  type: NodePort
  selector:
    app: ws-app
  # IMPORTANTE: SessionAffinity asegura que un usuario no "salte" 
  # entre pods y pierda la conexión del socket
  sessionAffinity: ClientIP 
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002